### ISSUE TITLE
Missing webcam images large and east/west

### ISSUE THREAD

**Issue by mfgtadmin** [lszt/web-2019#1]
small:
http://webcam.mfgt.ch/em.jpg
http://webcam.mfgt.ch/wm.jpg

large:
http://webcam.mfgt.ch/eh.jpg
http://webcam.mfgt.ch/wh.jpg

**Comment by pasutter** [comment]
Embedded a very small and simple lightbox.
http://dbrekalo.github.io/simpleLightbox/
